spring:
  messages:
    basename: messages,config.i18n.messages,errors

server:
    error:
        whitelabel:
            enabled: false
        include-binding-errors: always
        include-exception: true
        include-message: always
        include-stacktrace: always

